### ISSUE TITLE
Classification of Victory- and Honorcertificates

### ISSUE THREAD

**Issue by skyliam** [bjs-org/bjs-api#11]
I want to add a feature which returns which kind of certificate the student gets.
Do you have any suggestions where I should add it? A new controller?

**Comment by aykborstelmann** [comment]
You could rename the `StudentScoreController` to `StudentController` and add an endpoint `/paper` or `/classification` or any name you think is appropriate.

**Comment by aykborstelmann** [comment]
Actually this is a duplicate of #7. Please have a look at this there.

**Comment by aykborstelmann** [comment]
Wait with closing this issue, I want to show you something.
