### ISSUE TITLE
Categorization different papers

### ISSUE THREAD

**Issue by aykborstelmann** [bjs-org/bjs-api#7]
Each student gets and paper depending on its age level and achieved points. 
Our system has to categorize to winner-, honour- and participant-paper.

**Comment by aykborstelmann** [comment]
@skyliam I hope I didn't confuse you, but please work with this issue instead :wink:

**Comment by skyliam** [comment]
@aykborstelmann  oh i see im a bit stupid 😅

**Comment by skyliam** [comment]
@aykborstelmann I work on this feature first

**Comment by aykborstelmann** [comment]
Wait with closing this issue, I want to show you something

**Comment by aykborstelmann** [comment]
Thank you @skyliam
